// Convex API - Manually created to work with Next.js
// This mirrors what would be generated by Convex

import { makeFunctionReference } from "convex/server";

// Blog API
export const blog = {
  list: makeFunctionReference("blog:list"),
  getBySlug: makeFunctionReference("blog:getBySlug"),
  listAll: makeFunctionReference("blog:listAll"),
  getById: makeFunctionReference("blog:getById"),
  create: makeFunctionReference("blog:create"),
  update: makeFunctionReference("blog:update"),
  remove: makeFunctionReference("blog:remove"),
};

// Auth API
export const auth = {
  getUserRole: makeFunctionReference("auth:getUserRole"),
  isAdmin: makeFunctionReference("auth:isAdmin"),
  setUserRole: makeFunctionReference("auth:setUserRole"),
  removeUserRole: makeFunctionReference("auth:removeUserRole"),
};

// Export as api object for convenience
export const api = {
  blog,
  auth,
};

export const internal = api;
export const components = {};
